### ISSUE TITLE
设置 lintInWorker 为 true 后启动报错

### ISSUE THREAD

**Issue by Ttou** [ModyQyW/vite-plugin-eslint#20]
### 描述问题

![image](https://user-images.githubusercontent.com/4298437/209767506-acbc9078-193b-4176-a871-c91b6c1a8f15.png)

### 复现

https://stackblitz.com/edit/vitejs-vite-g1uayf

### 系统信息

```Shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
```

### 使用的包管理器

npm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/ModyQyW/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by ModyQyW** [comment]
@Ttou 非常感谢你指出这个问题！请试试 v3.1.4。

**Comment by Ttou** [comment]
@ModyQyW 可以了
